[PATCH] patch udev 009-010 rpm spec file
the following problem was introduced with udev 009:

[root@claw packages]# rpm -Uvh ~mh/rpm/RPMS/ppc/udev-010-1.ppc.rpm
Preparing...########################################### [100%]
   1:udev   ########################################### [100%]
error: unpacking of archive failed on file /usr/share/doc/udev-010/COPYING;3fe8a8e3: cpio: open failed - Permission denied

it's because the mode of the directory /usr/share/doc/udev-010/ is
0644. This is with yellodog-3.0.

the following patch fixes it: